	drop table categories if exists;
    drop table topics if exists;
    drop table votes if exists;

    
    create table categories (
       id bigint generated by default as identity,
        text varchar(75) not null,
        primary key (id)
    );

    
    create table topics (
       id bigint generated by default as identity,
        date_created timestamp not null,
        text varchar(254) not null,
        token varchar(255) not null,
        category_id bigint,
        primary key (id)
    );

    
    create table votes (
       id bigint generated by default as identity,
        date_created timestamp not null,
        ip varchar(255) not null,
        selection boolean not null,
        topic_id bigint,
        primary key (id)
    );

    
    alter table topics 
       add constraint FK3mind1ka66asw07vi2t2gxalm 
       foreign key (category_id) 
       references categories;

    
    alter table votes 
       add constraint FK64rthokp01qie35110defje4c 
       foreign key (topic_id) 
       references topics;